### ISSUE TITLE
Allow for changing a space's shorturl

### ISSUE THREAD

**Issue by dhergert** [birdietiger/publicspaces-webexteams#1]
Keeping same shortId when eurl bot removed and re-added can be a security concern.

Background: I added eurl bot to a space and had users use the short Id url to gain access.  I also temporarily exposed the space via the eurl.io website listing.

I wanted to remove the users that had added themselves and remove the bot, because some people erroneously joined and I wanted a different set of users to have access to the space.  When I re-added the bot, it got the same eurl shortId.  This allowed users who previously knew the shortId URL to regain access.  This can be a security concern.

I think either eurl should generate a new shortId when you remove/add the Bot, or allow for a new command to generate a new short url.

The code in question is
https://github.com/birdietiger/publicspaces-webexteams/blob/master/index.js#L2054

**Comment by birdietiger** [comment]
Congrats on being the first to post an issue! 

The UX thinking on this was based on early experiences where people would create marketing collateral using the url/qr and share with thousands. If someone inadvertently removed the bot and we generated a new id when it was added back... well, let's just say, it would be bad.

On my todo list for some time was a command to generate a new id to solve for your exact issue. You're just the first person to make the request. I'll add it as the next item in the backlog.

**Comment by birdietiger** [comment]
Added feature to create a new url and revert to previous url. https://github.com/birdietiger/publicspaces-webexteams/commit/fbcd5607f7dde3fd636b53894ae48e645e31896d

The feature has been deployed to production for Eurl.

**Comment by dhergert** [comment]
Oh thanks for jumping on that!  I actually started implementing a 'newurl' command to try and fix it for ya but you beat me to it! :)  I like your implementation of new and previous commands, allowing the admin to revert if needed. Thanks!
